# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5192ed40017853bba282c8cbea8012a5d382874b1a3fa01c521b8076b4455fcb1518868030acb957a1409c88115ee449f06aeebbede074db9d5598c50f4168b3

test:
  secret_key_base: 3d5d76b354a37a549960f78a68cb2ddc04bf992200e3569b6ac5f01f1c4fc6c259e7aefe913de1b4f0244aabe7d2b7cb92aa214dbd35c25ca42bf03edf6a72dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
